spring:
  application:
    name: redemption-engine

  datasource:
    url: ${REDEMPTION_DB_URL:jdbc:postgresql://${REDEMPTION_DB_HOST:localhost}:${REDEMPTION_DB_PORT:5432}/${REDEMPTION_DB_NAME:redemption_db}?currentSchema=redemption,public}
    username: ${REDEMPTION_DB_USERNAME:redemption_user}
    password: ${REDEMPTION_DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${IDEMPOTENCY_STORE_HOST:localhost}
      port: ${IDEMPOTENCY_STORE_PORT:6379}

server:
  port: 8083

loyalty:
  services:
    tiering-base-url: ${TIERING_SYSTEM_SERVICE_URL:http://localhost:8082}
    earning-base-url: ${EARNING_ENGINE_SERVICE_URL:http://localhost:8081}

logging:
  level:
    com.loyalty: DEBUG
