spring:
  application:
    name: analytics-reporting

  datasource:
    url: ${DATA_WAREHOUSE_URL:jdbc:postgresql://${DATA_WAREHOUSE_HOST:localhost}:${DATA_WAREHOUSE_PORT:5432}/${DATA_WAREHOUSE_NAME:analytics_dw}?currentSchema=analytics,public}
    username: ${DATA_WAREHOUSE_USERNAME:analytics_user}
    password: ${DATA_WAREHOUSE_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${MESSAGE_BROKER_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: analytics-dw-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8085

logging:
  level:
    com.loyalty: DEBUG
